
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */


#pragma once

#if !defined (__EV_EVINCE_VIEW_H_INSIDE__) && !defined (EVINCE_COMPILATION)
#error "Only <evince-view.h> can be included directly."
#endif

#include <glib-object.h>

#include <evince-document.h>

G_BEGIN_DECLS

/* enumerations from "ev-document-model.h" */
EV_PUBLIC
GType ev_sizing_mode_get_type (void) G_GNUC_CONST;
#define EV_TYPE_SIZING_MODE (ev_sizing_mode_get_type ())
EV_PUBLIC
GType ev_page_layout_get_type (void) G_GNUC_CONST;
#define EV_TYPE_PAGE_LAYOUT (ev_page_layout_get_type ())

/* enumerations from "ev-job-scheduler.h" */
EV_PUBLIC
GType ev_job_priority_get_type (void) G_GNUC_CONST;
#define EV_TYPE_JOB_PRIORITY (ev_job_priority_get_type ())

/* enumerations from "ev-jobs.h" */
EV_PUBLIC
GType ev_job_run_mode_get_type (void) G_GNUC_CONST;
#define EV_TYPE_JOB_RUN_MODE (ev_job_run_mode_get_type ())
EV_PUBLIC
GType ev_job_page_data_flags_get_type (void) G_GNUC_CONST;
#define EV_TYPE_JOB_PAGE_DATA_FLAGS (ev_job_page_data_flags_get_type ())
EV_PUBLIC
GType ev_job_thumbnail_format_get_type (void) G_GNUC_CONST;
#define EV_TYPE_JOB_THUMBNAIL_FORMAT (ev_job_thumbnail_format_get_type ())
G_END_DECLS

/* Generated data ends here */

