
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */


#pragma once

#if !defined (__EV_EVINCE_DOCUMENT_H_INSIDE__) && !defined (EVINCE_COMPILATION)
#error "Only <evince-document.h> can be included directly."
#endif

#include <glib-object.h>

#include "ev-macros.h"

G_BEGIN_DECLS

/* enumerations from "ev-annotation.h" */
EV_PUBLIC
GType ev_annotation_type_get_type (void) G_GNUC_CONST;
#define EV_TYPE_ANNOTATION_TYPE (ev_annotation_type_get_type ())
EV_PUBLIC
GType ev_annotation_text_icon_get_type (void) G_GNUC_CONST;
#define EV_TYPE_ANNOTATION_TEXT_ICON (ev_annotation_text_icon_get_type ())
EV_PUBLIC
GType ev_annotation_text_markup_type_get_type (void) G_GNUC_CONST;
#define EV_TYPE_ANNOTATION_TEXT_MARKUP_TYPE (ev_annotation_text_markup_type_get_type ())

/* enumerations from "ev-document-annotations.h" */
EV_PUBLIC
GType ev_annotations_save_mask_get_type (void) G_GNUC_CONST;
#define EV_TYPE_ANNOTATIONS_SAVE_MASK (ev_annotations_save_mask_get_type ())
EV_PUBLIC
GType ev_annotations_over_markup_get_type (void) G_GNUC_CONST;
#define EV_TYPE_ANNOTATIONS_OVER_MARKUP (ev_annotations_over_markup_get_type ())

/* enumerations from "ev-document-find.h" */
EV_PUBLIC
GType ev_find_options_get_type (void) G_GNUC_CONST;
#define EV_TYPE_FIND_OPTIONS (ev_find_options_get_type ())

/* enumerations from "ev-document-info.h" */
EV_PUBLIC
GType ev_document_layout_get_type (void) G_GNUC_CONST;
#define EV_TYPE_DOCUMENT_LAYOUT (ev_document_layout_get_type ())
EV_PUBLIC
GType ev_document_mode_get_type (void) G_GNUC_CONST;
#define EV_TYPE_DOCUMENT_MODE (ev_document_mode_get_type ())
EV_PUBLIC
GType ev_document_contains_js_get_type (void) G_GNUC_CONST;
#define EV_TYPE_DOCUMENT_CONTAINS_JS (ev_document_contains_js_get_type ())
EV_PUBLIC
GType ev_document_ui_hints_get_type (void) G_GNUC_CONST;
#define EV_TYPE_DOCUMENT_UI_HINTS (ev_document_ui_hints_get_type ())
EV_PUBLIC
GType ev_document_permissions_get_type (void) G_GNUC_CONST;
#define EV_TYPE_DOCUMENT_PERMISSIONS (ev_document_permissions_get_type ())
EV_PUBLIC
GType ev_document_info_fields_get_type (void) G_GNUC_CONST;
#define EV_TYPE_DOCUMENT_INFO_FIELDS (ev_document_info_fields_get_type ())

/* enumerations from "ev-document.h" */
EV_PUBLIC
GType ev_document_load_flags_get_type (void) G_GNUC_CONST;
#define EV_TYPE_DOCUMENT_LOAD_FLAGS (ev_document_load_flags_get_type ())
EV_PUBLIC
GType ev_document_error_get_type (void) G_GNUC_CONST;
#define EV_TYPE_DOCUMENT_ERROR (ev_document_error_get_type ())

/* enumerations from "ev-file-exporter.h" */
EV_PUBLIC
GType ev_file_exporter_format_get_type (void) G_GNUC_CONST;
#define EV_TYPE_FILE_EXPORTER_FORMAT (ev_file_exporter_format_get_type ())
EV_PUBLIC
GType ev_file_exporter_capabilities_get_type (void) G_GNUC_CONST;
#define EV_TYPE_FILE_EXPORTER_CAPABILITIES (ev_file_exporter_capabilities_get_type ())

/* enumerations from "ev-file-helpers.h" */
EV_PUBLIC
GType ev_compression_type_get_type (void) G_GNUC_CONST;
#define EV_TYPE_COMPRESSION_TYPE (ev_compression_type_get_type ())

/* enumerations from "ev-form-field.h" */
EV_PUBLIC
GType ev_form_field_text_type_get_type (void) G_GNUC_CONST;
#define EV_TYPE_FORM_FIELD_TEXT_TYPE (ev_form_field_text_type_get_type ())
EV_PUBLIC
GType ev_form_field_button_type_get_type (void) G_GNUC_CONST;
#define EV_TYPE_FORM_FIELD_BUTTON_TYPE (ev_form_field_button_type_get_type ())
EV_PUBLIC
GType ev_form_field_choice_type_get_type (void) G_GNUC_CONST;
#define EV_TYPE_FORM_FIELD_CHOICE_TYPE (ev_form_field_choice_type_get_type ())

/* enumerations from "ev-link-action.h" */
EV_PUBLIC
GType ev_link_action_type_get_type (void) G_GNUC_CONST;
#define EV_TYPE_LINK_ACTION_TYPE (ev_link_action_type_get_type ())

/* enumerations from "ev-link-dest.h" */
EV_PUBLIC
GType ev_link_dest_type_get_type (void) G_GNUC_CONST;
#define EV_TYPE_LINK_DEST_TYPE (ev_link_dest_type_get_type ())

/* enumerations from "ev-selection.h" */
EV_PUBLIC
GType ev_selection_style_get_type (void) G_GNUC_CONST;
#define EV_TYPE_SELECTION_STYLE (ev_selection_style_get_type ())

/* enumerations from "ev-transition-effect.h" */
EV_PUBLIC
GType ev_transition_effect_type_get_type (void) G_GNUC_CONST;
#define EV_TYPE_TRANSITION_EFFECT_TYPE (ev_transition_effect_type_get_type ())
EV_PUBLIC
GType ev_transition_effect_alignment_get_type (void) G_GNUC_CONST;
#define EV_TYPE_TRANSITION_EFFECT_ALIGNMENT (ev_transition_effect_alignment_get_type ())
EV_PUBLIC
GType ev_transition_effect_direction_get_type (void) G_GNUC_CONST;
#define EV_TYPE_TRANSITION_EFFECT_DIRECTION (ev_transition_effect_direction_get_type ())
G_END_DECLS

/* Generated data ends here */

