/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ENABLE_DBUS

#define ENABLE_MULTIMEDIA

#define ENABLE_NLS

#define EXTRA_GDK_PIXBUF_LOADERS_DIR "/usr/local/lib/x86_64-linux-gnu/evince/gdk-pixbuf/2.10.0"

#define GETTEXT_PACKAGE "evince"

#define GTKUNIXPRINT_ENABLED 1

#define HAVE_DESKTOP_SCHEMAS

#define HAVE_HIDPI_SUPPORT

#define HAVE_LIBGNOME_DESKTOP

#define HAVE_SPECTRE

/* Define if _NL_MEASUREMENT_MEASUREMENT is available */
#define HAVE__NL_MEASUREMENT_MEASUREMENT

#define PACKAGE_ICON_NAME "org.gnome.Evince"

#define PACKAGE_VERSION "43.alpha"

#define SIZEOF_INT 4

#define SIZEOF_LONG 8

#define SIZEOF_LONG_LONG 8

#define SIZEOF_SHORT 2

#define SIZEOF_VOID_P 8

#define STDC_HEADERS 1

#define VERSION "43.alpha"

#define WITH_GSPELL 1

#define WITH_KEYRING

#define _GNU_SOURCE 1

