
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */


#include "config.h"
#include "hdy-enums-private.h"
#include "hdy-stackable-box-private.h"
#include "hdy-settings-private.h"
/* enumerations from "hdy-settings-private.h" */
GType
hdy_system_color_scheme_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { HDY_SYSTEM_COLOR_SCHEME_DEFAULT, "HDY_SYSTEM_COLOR_SCHEME_DEFAULT", "default" },
            { HDY_SYSTEM_COLOR_SCHEME_PREFER_DARK, "HDY_SYSTEM_COLOR_SCHEME_PREFER_DARK", "prefer-dark" },
            { HDY_SYSTEM_COLOR_SCHEME_PREFER_LIGHT, "HDY_SYSTEM_COLOR_SCHEME_PREFER_LIGHT", "prefer-light" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("HdySystemColorScheme"), values);
    }
    return etype;
}
/* enumerations from "hdy-stackable-box-private.h" */
GType
hdy_stackable_box_transition_type_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { HDY_STACKABLE_BOX_TRANSITION_TYPE_OVER, "HDY_STACKABLE_BOX_TRANSITION_TYPE_OVER", "over" },
            { HDY_STACKABLE_BOX_TRANSITION_TYPE_UNDER, "HDY_STACKABLE_BOX_TRANSITION_TYPE_UNDER", "under" },
            { HDY_STACKABLE_BOX_TRANSITION_TYPE_SLIDE, "HDY_STACKABLE_BOX_TRANSITION_TYPE_SLIDE", "slide" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("HdyStackableBoxTransitionType"), values);
    }
    return etype;
}


/* Generated data ends here */

